# Generated by Django 4.0.3 on 2022-04-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_mypicture_remove_list_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mypicture',
        ),
        migrations.AddField(
            model_name='list',
            name='image',
            field=models.ImageField(default='user1.jpg', upload_to='photos'),
        ),
    ]
