# Generated by Django 4.0.3 on 2022-04-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_delete_mypicture_list_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
