# Generated by Django 4.0.3 on 2022-04-26 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_list_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
