# Generated by Django 4.0.3 on 2022-04-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_list_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.CharField(max_length=64),
        ),
    ]
